version: "2.7"

networks:
  inception:
    driver: bridge
# bridge is the default network driver
# bridge networks are usually used when your applications run in standalone containers that need to communicate

volumes:
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      type: none
      o: bind
      device: /home/wurrigon/data/mariadb

  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: /home/wurrigon/data/wordpress

services:
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress/
    env_file: .env
    container_name: wordpress
    restart: always
    volumes: 
      - wordpress:/var/www/html/wordpress
    networks: 
      - inception
    depends_on:
      - mariadb

  nginx:
    build: ./requirements/nginx/
    env_file: .env
    container_name: nginx
    restart: always
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "443:443"
  
  redis:
    build: ./requirements/bonus/redis/
    container_name: redis
    restart: always
    depends_on:
      - nginx
    networks:
      - inception
    ports:
      - "6379:6379"
    
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer/
    restart: always
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - wordpress
    ports:
      - "8080:8080"